Devops/trivy-fix Fixed the Vulnerability  (#209)
* Dockerfile Updated to debian and Couple of Vulnerability removed

* Update chainlit-ci.yaml

* Update Dockerfile to run the workflow

* Update Dockerfile

* Update Dockerfile to run the workflow

* Update chainlit-ci.yaml

* Update Dockerfile

* Updated Dockerfile to run the workflow

* Updated .trivyignore.yaml added the newer vulnerability

* Updated chainlit-ci.yaml

changed workflow run to main

* Update chainlit-cd.yaml

* Update chainlit-ci.yaml

* Update Dockerfile

* Updated the helm files

* Values back to normal

* Update chainlit-ci.yaml

* helm files chnaged

* added trivy latest vulnerabilty in .tricyignore.yaml

* Update chainlit-ci.yaml

* Update Dockerfile

* Update chainlit-ci.yaml

* Update Dockerfile

---------

Co-authored-by: anubhav299774 <anubhav@bastion.sftp.ustpace.com>
Co-authored-by: Vinay Kumar Reddy Varikuti <vinay.varikuti@ust.com>

diff --git a/.github/workflows/chainlit-cd.yaml b/.github/workflows/chainlit-cd.yaml
--- a/.github/workflows/chainlit-cd.yaml
+++ b/.github/workflows/chainlit-cd.yaml
@@ -40,6 +40,21 @@ jobs:
           else
             echo "AWS CLI already installed."
           fi
+      - name: Ensure SSH client and nc (netcat) are installed
+        run: |
+          if ! command -v ssh &> /dev/null; then
+            echo "ssh not found. Installing openssh-client..."
+            sudo apt-get update
+            sudo apt-get install -y openssh-client
+          else
+            echo "ssh client already installed."
+          fi
+          if ! command -v nc &> /dev/null; then
+            echo "nc (netcat) not found. Installing netcat-openbsd..."
+            sudo apt-get install -y netcat-openbsd
+          else
+            echo "nc (netcat) is already installed."
+          fi
 
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v2
