Feature/sf 4889 confluence (#210)
* Added the confluence integration

* Added confleunce credentials

* Modified the credentials

* Added python installation

* chore: bump minor version automatically

* Added default values for env variables

---------

Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>

diff --git a/.github/workflows/pr-code-check.yaml b/.github/workflows/pr-code-check.yaml
--- a/.github/workflows/pr-code-check.yaml
+++ b/.github/workflows/pr-code-check.yaml
@@ -36,6 +36,19 @@ jobs:
         curl -LsSf https://astral.sh/uv/install.sh | sh
         uv sync --only-group code_check
 
+    # Ensure Python is available and Install
+    - name: Ensure Python is available and Install
+      run: |
+        if ! command -v python &> /dev/null; then
+          echo "Python not found, installing..."
+          sudo apt-get update -y
+          sudo apt-get install -y python3 python3-pip
+          sudo ln -sf /usr/bin/python3 /usr/bin/python
+        else
+          echo "Python already installed:"
+          python --version
+        fi
+
     # Run ruff (lint), skipping $EXCLUDE_DIR
     - name: Run ruff (excluding ${{ env.EXCLUDE_DIR }})
       run: uv run ruff check . --exclude "${{ env.EXCLUDE_DIR }}"
